apiVersion: v1
kind: Namespace
metadata:
  name: demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
        - name: getting-started
          image: docker/getting-started

---

apiVersion: v1
kind: Service
metadata:
  name: getting-started-entrypoint
  namespace: demo
spec:
  selector:
    app: getting-started
  ports:
    - port: 8080
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: getting-started-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: selfsigned-issuer
spec:
  tls:
    - hosts:
        - getting-started.local
      secretName: selfsigned-secret
  rules:
    - host: getting-started.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: getting-started-entrypoint
                port:
                  number: 8080
  ingressClassName: nginx

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: demo
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: demo
spec:
  secretName: selfsigned-secret
  duration: 170000h
  renewBefore: 72h
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  commonName: getting-started.local
  isCA: true
  dnsNames:
    - getting-started.local
